package sync

import (
	"os"
	"path/filepath"
	"testing"
)

// `expected_untracked` / `expected_uncommitted` declare local residue that is
// not news (DESIGN §3.6). They change what sync reports and whether it attempts
// a move; they never change what it protects.

func TestExpectedPathMatchesFullPathAndBaseName(t *testing.T) {
	cases := []struct {
		patterns []string
		path     string
		want     bool
	}{
		{nil, "x.plugin.zsh", false},
		{[]string{"*.plugin.zsh"}, "x.plugin.zsh", true},
		// path.Match doesn't cross "/", so the base-name test is what makes a
		// pattern work wherever a generator drops the file.
		{[]string{"*.plugin.zsh"}, "nested/deep/x.plugin.zsh", true},
		{[]string{"build/*"}, "build/stamp", true},
		{[]string{"build/*"}, "src/stamp", false},
		{[]string{"stamp"}, "build/stamp", true},
		{[]string{"*"}, "anything/at/all", true},
		{[]string{"*.zwc"}, "notes.txt", false},
	}
	for _, c := range cases {
		if got := expectedPath(c.patterns, c.path); got != c.want {
			t.Errorf("expectedPath(%v, %q) = %v, want %v", c.patterns, c.path, got, c.want)
		}
	}
}

// TestExpectedUntrackedSuppressesTheWarning is the powerlevel10k case: a file
// regenerated by something outside the repo, which the vendor will never
// .gitignore for you.
func TestExpectedUntrackedSuppressesTheWarning(t *testing.T) {
	_, clone, run := setupUpstreamRepo(t, `expected_untracked = ["*.plugin.zsh"]`)
	must(t, os.WriteFile(filepath.Join(clone, "thing.plugin.zsh"), []byte("shim\n"), 0o644))

	res := run()
	if res.Outcome != UpToDate {
		t.Fatalf("outcome = %v, want UpToDate (an expected file is not news); actions=%v", res.Outcome, res.Actions)
	}
	if !exists(filepath.Join(clone, "thing.plugin.zsh")) {
		t.Errorf("expected_untracked must not cause the file to be removed")
	}
}

// TestExpectedUntrackedStillReportsOthers: the reason this is a pattern list and
// not a switch — declaring one file expected must not blind the repo to the next
// unexpected one.
func TestExpectedUntrackedStillReportsOthers(t *testing.T) {
	_, clone, run := setupUpstreamRepo(t, `expected_untracked = ["*.plugin.zsh"]`)
	must(t, os.WriteFile(filepath.Join(clone, "thing.plugin.zsh"), []byte("shim\n"), 0o644))
	must(t, os.WriteFile(filepath.Join(clone, "real-work.txt"), []byte("draft\n"), 0o644))

	res := run()
	if res.Outcome != Attention {
		t.Fatalf("outcome = %v, want Attention; actions=%v", res.Outcome, res.Actions)
	}
	if want := "1 untracked file(s)"; res.Detail != want {
		t.Errorf("detail = %q, want %q (only the undeclared file counts)", res.Detail, want)
	}
}

// TestExpectedUncommittedDoesNotBlockTheUpdate: the asymmetry with untracked.
// Uncommitted changes block, so suppressing only the *report* would leave the
// branch silently stalled forever. Declaring the file expected has to let the
// fast-forward be attempted, and git arbitrates from there.
func TestExpectedUncommittedDoesNotBlockTheUpdate(t *testing.T) {
	origin, clone, run := setupUpstreamRepo(t, `expected_uncommitted = ["stamp.txt"]`)
	writeCommit(t, clone, "stamp.txt", "v1\n", "add stamp")
	git(t, clone, "push", "-q", "origin", "main")
	must(t, os.WriteFile(filepath.Join(clone, "stamp.txt"), []byte("locally regenerated\n"), 0o644))

	// Advance origin on a *different* file, so the fast-forward doesn't touch
	// the locally-modified one.
	want := advanceOrigin(t, origin, "other.txt", "two\n", "two")

	res := run()
	if got := revParse(t, clone, "main"); got != want {
		t.Errorf("main = %s, want %s (an expected modification must not stall the branch)", got, want)
	}
	body, err := os.ReadFile(filepath.Join(clone, "stamp.txt"))
	must(t, err)
	if string(body) != "locally regenerated\n" {
		t.Errorf("stamp.txt = %q, want the local modification preserved", body)
	}
	if res.Outcome != Updated {
		t.Fatalf("outcome = %v, want Updated; actions=%v", res.Outcome, res.Actions)
	}
}

// TestExpectedUncommittedStillReportsOthers: same containment as untracked — an
// undeclared modification still blocks and still reports.
func TestExpectedUncommittedStillReportsOthers(t *testing.T) {
	origin, clone, run := setupUpstreamRepo(t, `expected_uncommitted = ["stamp.txt"]`)
	writeCommit(t, clone, "stamp.txt", "v1\n", "add stamp")
	git(t, clone, "push", "-q", "origin", "main")
	must(t, os.WriteFile(filepath.Join(clone, "stamp.txt"), []byte("regenerated\n"), 0o644))
	must(t, os.WriteFile(filepath.Join(clone, "a"), []byte("hand edit\n"), 0o644))

	before := revParse(t, clone, "main")
	advanceOrigin(t, origin, "other.txt", "two\n", "two")

	res := run()
	if got := revParse(t, clone, "main"); got != before {
		t.Errorf("main moved to %s, want it held at %s (an undeclared modification still blocks)", got, before)
	}
	if res.Outcome != Attention {
		t.Fatalf("outcome = %v, want Attention; actions=%v", res.Outcome, res.Actions)
	}
	if want := "1 uncommitted change(s) — update skipped"; res.Detail != want {
		t.Errorf("detail = %q, want %q (only the undeclared file counts)", res.Detail, want)
	}
}

// TestExpectedUncommittedStillStopsForcePull is the protection half, and the one
// place the two options deliberately differ from "just don't tell me". An
// expected file is still work that exists nowhere else, so force_pull's
// reset --hard must still refuse — sync attempting a *safe* move is not the same
// as sync being allowed to destroy the file.
func TestExpectedUncommittedStillStopsForcePull(t *testing.T) {
	origin, clone, run := setupUpstreamRepo(t, `expected_uncommitted = ["a"]
force_pull = ["main"]`)
	must(t, os.WriteFile(filepath.Join(clone, "a"), []byte("locally regenerated\n"), 0o644))

	// Advance origin on the same file, so a fast-forward can't happen and the
	// force_pull path is the one that decides.
	before := revParse(t, clone, "main")
	advanceOrigin(t, origin, "a", "upstream change\n", "upstream change")

	res := run()
	if got := revParse(t, clone, "main"); got != before {
		t.Errorf("main moved to %s, want it held at %s (force_pull must not reset over local work)", got, before)
	}
	body, err := os.ReadFile(filepath.Join(clone, "a"))
	must(t, err)
	if string(body) != "locally regenerated\n" {
		t.Errorf("a = %q, want the local modification preserved — expected_uncommitted is not consent to destroy it", body)
	}
	if res.Outcome != Attention {
		t.Fatalf("outcome = %v, want Attention; actions=%v", res.Outcome, res.Actions)
	}
}

// TestExpectedInheritsFromRoot: the shape that actually solves the plugins case —
// one declaration on the root covers every repo under it, including ones
// discovered rather than declared.
func TestExpectedInheritsFromRoot(t *testing.T) {
	_, clone, run := setupUpstreamRepoWithRootSettings(t, `expected_untracked = ["*.plugin.zsh"]`)
	must(t, os.WriteFile(filepath.Join(clone, "thing.plugin.zsh"), []byte("shim\n"), 0o644))

	res := run()
	if res.Outcome != UpToDate {
		t.Fatalf("outcome = %v, want UpToDate (root-level declaration must inherit); actions=%v", res.Outcome, res.Actions)
	}
}
